const actionTypes = {
  GET_ROLE_LIST_REQUEST: "GET_ROLE_LIST_REQUEST",
  GET_ROLE_LIST_SUCCESS: "GET_ROLE_LIST_SUCCESS",
  GET_ROLE_LIST_ERROR: "GET_ROLE_LIST_ERROR",
  ADD_ROLE_REQUEST: "ADD_ROLE_REQUEST",
  ADD_ROLE_SUCCESS: "ADD_ROLE_SUCCESS",
  ADD_ROLE_ERROR: "ADD_ROLE_ERROR",
  DELETE_ROLE_REQUEST: "DELETE_ROLE_REQUEST",
  DELETE_ROLE_SUCCESS: "DELETE_ROLE_SUCCESS",
  DELETE_ROLE_ERROR: "DELETE_ROLE_ERROR",
  UPDATE_ROLE_REQUEST: "UPDATE_ROLE_REQUEST",
  UPDATE_ROLE_SUCCESS: "UPDATE_ROLE_SUCCESS",
  UPDATE_ROLE_ERROR: "UPDATE_ROLE_ERROR",
};

export default actionTypes;
