const actionTypes = {
  GET_ROLE_LIST_REQUEST: "GET_ROLE_LIST_REQUEST",
  GET_ROLE_LIST_SUCCESS: "GET_ROLE_LIST_SUCCESS",
  GET_ROLE_LIST_ERROR: "GET_ROLE_LIST_ERROR",
};

export default actionTypes;
