const actionTypes = {
  GET_TUTORIAL_LIST_REQUEST: "GET_TUTORIAL_LIST_REQUEST",
  GET_TUTORIAL_LIST_SUCCESS: "GET_TUTORIAL_LIST_SUCCESS",
  GET_TUTORIAL_LIST_ERROR: "GET_TUTORIAL_LIST_ERROR",
  GET_TUTORIAL_BY_ID_REQUEST: "GET_TUTORIAL_BY_ID_REQUEST",
  GET_TUTORIAL_BY_ID_SUCCESS: "GET_TUTORIAL_BY_ID_SUCCESS",
  GET_TUTORIAL_BY_ID_ERROR: "GET_TUTORIAL_BY_ID_ERROR",
  DELETE_TUTORIAL_REQUEST: "DELETE_TUTORIAL_REQUEST",
  DELETE_TUTORIAL_SUCCESS: "DELETE_TUTORIAL_SUCCESS",
  DELETE_TUTORIAL_ERROR: "DELETE_TUTORIAL_ERROR",
  UPDATE_TUTORIAL_REQUEST: "UPDATE_TUTORIAL_REQUEST",
  UPDATE_TUTORIAL_SUCCESS: "UPDATE_TUTORIAL_SUCCESS",
  UPDATE_TUTORIAL_ERROR: "UPDATE_TUTORIAL_ERROR",
};

export default actionTypes;
